<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

<!--    <Target Name="CopyFiles" AfterTargets="Build">-->
<!--        <ItemGroup>-->
<!--            <OutputFiles Include="$(OutputPath)**\*.dll" />-->
<!--        </ItemGroup>-->
<!--        <Copy SourceFiles="@(OutputFiles)" DestinationFolder="$(OutputPath)..\..\..\..\..\..\Kit"/>-->
<!--    </Target>-->
    
</Project>
