global using System;
global using System.Collections.Immutable;
global using System.Linq;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.CSharp;
global using Microsoft.CodeAnalysis.CSharp.Syntax;
global using Microsoft.CodeAnalysis.Diagnostics;
global using ODK.Netcode.Enums;
global using ODK.Roslyn.Extensions;